const colors = [
  { name: "أبيض", background: "bg-white" },
  { name: "أسود", background: "bg-black" },
  { name: "فضي", background: "bg-gray-200" },
  { name: "رمادي", background: "bg-gray-400" },
  { name: "أسمنتي", background: "bg-gray-500" },
  { name: "أحمر", background: "bg-red-500" },
  { name: "خمري", background: "bg-red-600" },
  { name: "أصفر", background: "bg-yellow-500" },
  { name: "برتقالي", background: "bg-orange-500" },
  { name: "ذهبي", background: "bg-yellow-300" },
  { name: "برونزي", background: "bg-yellow-600" },
  { name: "بني", background: "bg-amber-950" },
  { name: "بيج", background: "bg-yellow-200" },
  { name: "أزرق", background: "bg-blue-500" },
  { name: "كحلي", background: "bg-blue-700" },
  { name: "أزرق فاتح", background: "bg-blue-300" },
  { name: "أخضر", background: "bg-green-500" },
  { name: "زيتي", background: "bg-green-600" },
  { name: "تركواز", background: "bg-teal-500" },
  { name: "بترولي", background: "bg-teal-600" },
  { name: "بنفسجي", background: "bg-purple-500" },
];

module.exports = colors;
