version: "3.9"

services:
  web:
    restart: always
    build: .
    command: node server.js
    volumes:
      - ./public/uploads:/my-space/public/uploads
    ports:
      - 80:3000
      - 443:3000
      - 3000:3000
    env_file:
      - .env
