version: "3.9"

services:
  web:
    restart: always
    build: .
    command: node server.js
    volumes:
      - ./public/uploads:/my-space/public/uploads
    ports:
      - 3000:3000
    env_file:
      - .env
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public/uploads:/my-space/public/uploads
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - web
  #certbot:
    #image: certbot/certbot
    #container_name: certbot
    #volumes:
      #- certbot-etc:/etc/letsencrypt
      #- certbot-var:/var/lib/letsencrypt
      #- web-root:/var/www/html
    #depends_on:
      #- webserver
    #command: certonly --webroot --webroot-path=/var/www/html --email daleelalhurra@gmail.com --agree-tos --no-eff-email --force-renewal -d daleelalhurra.com  -d www.daleelalhurra.com
volumes:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: ./dhparam/
      o: bind


